// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoCRUD.WEB.Models.DAL;

namespace ProyectoCRUD.WEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220407043400_toro")]
    partial class toro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoCRUD.WEB.Models.Entities.Maquinaria", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amperaje")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CajaReductora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Componentes")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreMaquina");

                    b.Property<string>("Potencia")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProtectorTermico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Velocidad")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Voltaje")
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("IdMaquina");

                    b.ToTable("Maquinas");
                });
#pragma warning restore 612, 618
        }
    }
}
